" .vimrc -- the bare necessities
filetype plugin indent on      " Enable filetype plugins/indentation
syntax on                      " Syntax highlighting on
set softtabstop=4              " <TAB> is 4 spaces (when expandtab set)
set shiftwidth=4               " >> will indent 4 spaces
set expandtab                  " Needed to replace <TAB> with spaces
set autoindent                 " Indent carries over on new line
set smarttab                   " Use shiftwidth for <TAB> and <BS>
set hlsearch                   " Highlight searches
set incsearch                  " Incrementally search
set backspace=indent,eol,start " Backspace should function as expected
set ttimeout                   " Timeout on esc keycodes
set ttimeoutlen=30             " Low timeout to avoid <ESC> delay
set modelines=0                " Disable modelines for security
set history=10000              " Remember last 1000 :commands
set scrolloff=3                " Scroll at 3 rows from edge of screen
set wildmenu                   " Visual completion for command mode
set showcmd                    " Show the command being typed
set laststatus=2               " Always show the statusbar
set noequalalways              " Don't resize split on open/close event
set listchars=tab:>-,trail:~,eol:$  " Nicer whitespace
set hidden                     " Allow unsaved buffers

if v:progname =~# 'vim$'
    runtime! improved.vim        " put the IM in VIM
elseif has('packages')
    set pp-=~/.vim
    set pp-=~/.vim/after
endif
