#!/bin/sh
# ~/.shrc -- a config for all POSIX shells
[ -z "$PS1" ] && return  # Exit early if non-interactive

# Crucial exports
PATH=$HOME/bin:$PATH     # Put ~/bin on the for personal scripts
EDITOR='vi'              # $EDITOR, the most important (personal) of exports
VISUAL='vi'              # Some programs give priority to this
MANPAGER="less"          # less is more

export PATH EDITOR VISUAL MANPAGER

# Build up a somewhat fancy prompt (with SSH and error code indicators!)
if [ -n "$SSH_CLIENT" ]; then
    SSH_PROMPT="$USER@$(hostname -s):"
fi

last_err() {
    err="$?"
    if [ $err -ne "0" ]; then
        echo "[$err] "
    fi
}

PS1='$(last_err)[${SSH_PROMPT}${PWD}]\$ '
PS2="> "

[ -r "$HOME/.aliases" ] && . "$HOME/.aliases"
