#!/bin/sh
# ~/.shrc -- a config for all POSIX shells
[ -z "$PS1" ] && return  # Exit early if non-interactive

# Crucial exports
PATH=$HOME/bin:$PATH     # Put ~/bin on the for personal scripts
EDITOR='vi'              # $EDITOR, the most important (personal) of exports
VISUAL='vi'              # Some programs give priority to this
PAGER='less'             # less is more
export PATH EDITOR VISUAL PAGER

# Shell vars
HISTFILE=${HISTFILE:="$HOME/.sh_histo"}  # Don't override bash_history
HOSTNAME="$(hostname -s)"

# Prompt
last_err() {
    err="$?"
    if [ $err -ne "0" ]; then
        echo "($err)"
    fi
}
PS1='$(last_err)[${USER}@${HOSTNAME}]\$ '

# Includes
[ -r "$HOME/.aliases" ] && . "$HOME/.aliases"
