" Disable visual bells
set noerrorbells visualbell t_vb=
autocmd GUIEnter * set visualbell t_vb=

" Pretty printing
set printoptions=left:1in,right:1in,paper:letter
set printfont=Consolas:h11

" Minimal UI
set guioptions=                 " Don't show guioptions (toolbar, scrollbar,..)
set guicursor=a:blinkon0        " Don't blink the cursor (not my thang)

" Font that doesn't hurt my eyes at a size depending on the screen
if has('gui_macvim')
    set guifont=Inconsolata:h15
else
    set guifont=Inconsolata:h11
end

" Bigger size on startup
set lines=50
set columns=100
