"line numbers on
set number

"tab is really spaces
set expandtab

"4 spaces per tab
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent
set smarttab

"backspace should function as expected
set backspace=indent,eol,start

"search highlighting and incremental search
set hlsearch
set incsearch

filetype plugin indent on

" OTHER
" Link clipboard to mac
set clipboard=unnamed

"For security (modeline vulnerability)
set modelines=0

" Encoding
set encoding=utf-8

" Show whitespace with 'set: list' (disable: set: nolist)
set listchars=space:·,tab:>–,trail:~,eol:¬

" Prevent {}, (), [] commands from opening folds
set foldopen-=block

" Prevent windows resizing when split opened/closed
set noequalalways

" Show the command being typed
set showcmd
set history=1000

" More visual completion for command mode
set wildmenu

" Set key code timeout to be less to avoid <ESC> delay
set ttimeout
set ttimeoutlen=30

" Scroll when cursor gets within 5 rows of screen end
set scrolloff=5

" When in MacVim don't show the scrollbars
set guioptions-=r
set guioptions-=L

" Persistent undo
if(has('persistent_undo') && !empty(finddir('~/.vim/undo', '~')))
    set undodir=~/.vim/undo/
    set undofile
    set undolevels=1000
    set undoreload=10000
endif

" Backup files to ~/.vim/swp if present, else .
set directory=~/.vim/swp,.

" Source helper files
" Only load plugins if vim-plug installed!
if filereadable(expand("~/.vim/autoload/plug.vim"))
    source ~/.vim/plugins.vim
    source ~/.vim/pluginsettings.vim
endif
source ~/.vim/theme.vim
source ~/.vim/functions.vim
source ~/.vim/keys.vim
