# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# zsh theme
ZSH_THEME="refined"

# Zsh plugins ( Example format: plugins=(rails git textmate ruby lighthouse) )
# note: zsh-syntax must be last!
plugins=(git zsh-syntax-highlighting docker)

source $ZSH/oh-my-zsh.sh

export DEFAULT_USER="$(whoami)"

# prevent zsh from renaming tmux windows
DISABLE_AUTO_TITLE="true"

# export editor for tmuxinator
export EDITOR="vim"

# 10ms for key sequences
KEYTIMEOUT=1

# vi keymap in terminal
bindkey -v

# backspace works past insert mode location
bindkey '^?' backward-delete-char

# ctrl-r starts searching history backward
bindkey '^r' history-incremental-search-backward

# Indicate vi mode!
local VI_PROMPT_APPEND_FILE=~/.akarledots/zsh/vi_prompt_append.zsh
if [[ -f "$VI_PROMPT_APPEND_FILE" ]]; then
    source "$VI_PROMPT_APPEND_FILE"
fi

# alias for homebrew versions of things
# alias ctags='/usr/local/Cellar/ctags/5.8_1/bin/ctags'
# alias python python2

# other alias'
alias dps="docker ps -a"

# ITALICS UPDATE: may break ssh?
if [ $TERM = 'xterm-256color-italic' ]; then
    alias ssh="TERM='xterm-256color' ssh"
    alias vsh="TERM='xterm-256color' vagrant ssh"
else
    alias vsh="vagrant ssh"
fi

alias vsus="vagrant suspend"
alias vup="vagrant up"

# cd to a parent directory
function pcd { cd ${PWD%/$1/*}/$1; }
