#!/usr/bin/env bash

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
  colorflag="--color"
else # macOS `ls`
  colorflag="-G"
fi

# ls aliases
alias ls='ls ${colorflag}'
alias l='ls -lAh ${colorflag}'
alias ll='ls -lh ${colorflag}'

# Git aliases
alias ga='git add'
alias gc='git commit --verbose'
alias gd='git diff'
alias gp='git push'
alias gs='git status'
alias gst='git status'
alias gl='git pull'
alias gco='git checkout'
alias gf='git fetch'
alias glg='git log --stat'
alias g_='git stash'
alias g_p='git stash pop'

# Git completion for aliases
__git_complete ga _git_add
__git_complete gco _git_checkout
__git_complete gd _git_diff
__git_complete ga _git_add

# Alias vim / vi to nvim if there
if [ -x "$(command -v nvim)" ]; then
  alias vi="nvim"
  alias vim="nvim"
fi

# Security aliases
alias sudovim='sudo vim -u NONE'

# Common cd aliases
alias cddv='cd ~/.vim'

# grep
alias grep='grep --color'
