#!/usr/bin/env bash
# Stripped down version of https://github.com/mathiasbynens/dotfiles/
# Modified for my current uses / level of understanding

# if you got xterm-256, export it!
if infocmp xterm-256color >/dev/null 2>&1; then
    # override xterm-256 if in tmux
    if ! [ -z "$TMUX" ]; then
        export TERM=tmux-256color
    else
        export TERM=xterm-256color
    fi
fi

function parse_git_dirty() {
  [[ $(git status 2> /dev/null | tail -n1) != *"working directory clean"* ]] && \
  [[ $(git status 2> /dev/null | tail -n1) != *"working tree clean"* ]] && echo "*"
}

function parse_git_branch() {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1$(parse_git_dirty)/"
}

# get colors from tput (else hardcode them)
if tput setaf 1 &> /dev/null; then tput sgr0
    if [[ $(tput colors) -ge 16 ]] 2>/dev/null; then
        MAGENTA="\[$(tput setaf 5)\]"
        ORANGE="\[$(tput setaf 11)\]"
        GRAY="\[$(tput setaf 8)\]"
        BLUE="\[$(tput setaf 12)\]"
        BOLD="\[$(tput bold)\]"
        RESET="\[$(tput sgr0)\]"

        export PS1="\n$BOLD$BLUE\w $RESET$GRAY\$(parse_git_branch)"$'\n'"$BOLD$MAGENTA\$ $RESET"
        export PS2="$ORANGE→ $RESET"
    else
        # TODO: write better case for too few colors...
        export PS1="\w\n\$ "
        export PS2="> "
    fi
else
    # TODO: write better case for no tput...
    export PS1="\w\n\$ "
    export PS2="> "
fi
