#!/usr/bin/env bash
# Stripped down version of https://github.com/mathiasbynens/dotfiles/
# Modified for my current uses / level of understanding

# if you got xterm-256, export it!
if infocmp xterm-256color >/dev/null 2>&1; then
    # override xterm-256 if in tmux
    if ! [ -z "$TMUX" ]; then
        export TERM=tmux-256color
    else
        export TERM=xterm-256color
    fi
fi

if [ -n "$SSH_CLIENT" ]; then
    ssh_text="[$USER@$(hostname)] "
fi

function parse_git_dirty() {
    [ "$(git status --porcelain=v1 2> /dev/null)" ] && echo "*"
}

function parse_git_branch() {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1$(parse_git_dirty)/"
}

# Preferred Prompt: Fancy with colors from tput
if tput setaf 1 &> /dev/null; then tput sgr0
    if [[ $(tput colors) -ge 16 ]] 2>/dev/null; then
        SET_PREFERRED_PROMPT=1
        MAGENTA="\[$(tput setaf 5)\]"
        ORANGE="\[$(tput setaf 11)\]"
        GRAY="\[$(tput setaf 8)\]"
        BLUE="\[$(tput setaf 12)\]"
        BOLD="\[$(tput bold)\]"
        RESET="\[$(tput sgr0)\]"

        export PS1="$BOLD$BLUE\w $RESET$GRAY${ssh_text}\$(parse_git_branch)"$'\n'"$BOLD$MAGENTA\$ $RESET"
        export PS2="$ORANGE> $RESET"
    fi
fi

# Fallback Option: No colors, No Git
if [ -z $SET_PREFERRED_PROMPT ]; then
    export PS1="\w\n${ssh_text}\$ "
    export PS2="> "
fi

# This command runs after each issuing of PS1
# Used to add a newline after each prompt
export PROMPT_COMMAND="echo"
