#!/usr/bin/env bash
# Aliases specific to bash

# Git completion for aliases
if [ -n "$(type -t __git_complete)" ] && [ "$(type -t __git_complete)" == "function" ]; then
    __git_complete ga _git_add
    __git_complete gco _git_checkout
    __git_complete gd _git_diff
    __git_complete gr _git_rebase
    __git_complete gb _git_branch
fi

alias rb='source ~/.bashrc'
