#!/usr/bin/env bash
# .bashrc
# The way I like to roll in the shell

# If not running interactively, don't do anything
[ -z "$PS1" ] && return
[[ $- != *i* ]] && return  # I'm paranoid...

# Disable XON/XOFF to allow forward search w CTRL-S
stty -ixon

# History Settings
shopt -s histappend    # append to the history file, don't overwrite it
HISTSIZE=10000         # Max lines in history (in memory)
HISTFILESIZE=200000    # Max size of the history file
HISTIGNORE=fg:pwd:ls   # Don't store common commands in history
HISTCONTROL=ignoreboth # Don't store (1) duplicate commands in history
                       #   AND don't store lines beginning with space

PROMPT_COMMAND="echo; history -a"

# Other Settings
shopt -s checkwinsize  # check win size after each cmd, update if needed

# Custom find function
function ff {
    find . -name "*$1*"
}

# Custom w3m seraches
function aw { w3m "https://wiki.archlinux.org/index.php?search=$1"; }
function ddg { w3m "https://duckduckgo.com/lite?q=$1"; }

# $EDITOR, the most important export of course
if [ -x "$(command -v nvim)" ]; then
    export EDITOR="nvim"
    export MANPAGER="nvim -u NORC -c 'set ft=man' -"
else
    export EDITOR="vim"
fi

# Source helper files, both mine and other's
function source_if_exists {
    if [ -r "$1" ]; then
        source "$1"
    fi
}

source_if_exists "$HOME/.bash/git-completion.bash" # Git Completion
source_if_exists "$HOME/.aliases"                  # Aliases (source after Git Completion!)
source_if_exists "$HOME/.bash_prompt"              # Personal Prompt
source_if_exists "$HOME/.bashrc.local"             # System specific settings
