#!/usr/bin/env bash

# Add Homebrew `/usr/local/bin` and User `~/bin` to the `$PATH`
PATH=/usr/local/bin:$PATH
PATH=$HOME/bin:$PATH

# Add cargo to path
PATH="$HOME/.cargo/bin:$PATH"

# Export it!
export PATH
